# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: Learning Portal
site_description: Choreo Learning Portal
site_author: WSO2
site_url: https://wso2.com/choreo/docs

# Repository
repo_name: wso2/docs-choreo-dev
repo_url: https://github.com/wso2/docs-choreo-dev/
edit_uri: https://github.com/wso2/docs-choreo-dev/edit/dev/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: ©2022 WSO2 LLC.

# Configuration
theme:
  name: material
  custom_dir: theme/material
  palette:
    primary: indigo
    accent: indigo
  logo: images/logo.svg
  favicon: images/favicon.png
  slack: images/help-slack-icon.svg
  choreo_logo: images/choreo-logo-icon.svg
  highlightjs: true
  feature:
    tabs: true
  font:
    text: 'Montserrat'
  language: 'en'
#Breaks build if there's a warning
strict: false
# Navigation
nav:
  - Home: index.md
  - Get Started:
      - What is Choreo?: get-started/what-is-choreo.md
      - Quick Start Guide: get-started/quick-start-guide.md
      - Tutorials: 
          - Create Your First REST API: get-started/tutorials/create-your-first-rest-api.md
          - Expose an Existing API via a REST API Proxy: get-started/tutorials/create-your-first-rest-api-proxy.md
          - Create Your First Webhook: get-started/tutorials/create-your-first-webhook.md
          - Connect Your Own GitHub Repository to Choreo: get-started/tutorials/connect-your-own-github-repository-to-choreo.md
          - Connect Your Existing Ballerina Project to Choreo: get-started/tutorials/connect-your-existing-ballerina-project-to-choreo.md
          - Deploy a Containerized Choreo Component: get-started/tutorials/deploy-a-containerized-choreo-component.md
  - Develop:
      - Components:
          - REST APIs: develop/components/rest-api.md
          - API Proxies: develop/components/api-proxies.md
          - Webhooks: develop/components/webhook.md
          - Scheduled Tasks: develop/components/scheduled-tasks.md
          - GraphQL APIs: develop/components/graphql-api.md
      - Run and Test:
          - Performance Analysis: develop/run-and-test/performance-analysis.md
      - Explore Code Editor:
          - Construct Statements: develop/explore-code-editor/construct-statements.md    
          - Define Configurable Variables: develop/explore-code-editor/define-configurable-variables.md
          - Handle Non-Ballerina Files in Choreo: develop/explore-code-editor/handle-non-ballerina-files-in-choreo.md
      - Advanced Topics:
          - Manage Connectors: develop/advanced-topics/manage-connectors.md
  - Consume:
      - Overview: consume/developer-portal.md
      - Manage Application: consume/manage-application.md
      - Manage Subscription: consume/manage-subscription.md
      - Test API: consume/test-api.md
  - Marketplace: marketplace.md
  - Observe and Analyze:
      - Observe:
         - Observability Overview: observe-and-analyze/observe/observability-overview.md
#        - View Logs: observability/view-logs.md
         - Root Cause Analysis: observe-and-analyze/observe/root-cause-analysis.md
      - Analyze: 
          - View API Insights: observe-and-analyze/analyze/view-api-insights.md
          - Generate Custom Reports: observe-and-analyze/analyze/generate-custom-reports.md
          - Configure Alerts: observe-and-analyze/analyze/configure-alerts.md
          - Choreo Insights API: observe-and-analyze/analyze/choreo-insights-api.md
          - Programmatic Access to Choreo Insights API: observe-and-analyze/analyze/programmatic-access-choreo-insights-api.md
  - Alerts: alerts.md
  - DevOps: devops/devops-portal.md
  - Administer:
      - Connect to an External Identity Provider: administer/connect-to-an-external-identity-provider.md  
      - Configure a Custom Domain for Developer Portal: administer/customize-developer-portal-domain.md
      - Configure Enterprise Login: administer/configure-enterprise-login.md
  - References:
     - Connect with Protected Third Party Applications: references/connect-with-protected-third-party-applications.md
# - Choreo DevOps: devops/overview.md
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  - markdown_include.include:
      base_path: docs
plugins:
  - search
  - markdownextradata: {}
  - redirects:
      redirect_maps:
          'manage/developer-portal.md': 'https://wso2.com/choreo/docs/developer-portal/developer-portal/' 
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
  - assets/css/prism.css
  - assets/lib/json-formatter/json-formatter.css
extra_javascript:
  - assets/lib/json-formatter/json-formatter.umd.js
  - assets/lib/highlightjs/highlight.min.js
  - assets/lib/prism/prism.js
  - assets/js/theme.js
  - assets/js/prism-ballerina.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 1.0.0
  #base_path: http://localhost:8000
